name: .NET

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Motivo'
        # Default value if no value is explicitly provided
        default: 'Test'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./Web.Client
      run: dotnet restore
    - name: Build
      working-directory: ./Web.Client
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Web.Client
      run: dotnet test --no-build --verbosity normal
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'buenotest.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy dev
    
